{
  "website": "http://ob-mc.net", 
  "commands": {
    "mw": {
      "usage": "none", 
      "description": "Spigot/Bukkit plugin to launch fireworks when a player joins the server.", 
      "aliases": []
    }
  }, 
  "version": "1.0",
  "api-version": "1.21", 
  "name": "OBFireworksOnJoin", 
  "author": "Fahrenheit451", 
  "main": "net.obmc.OBFireworksOnJoin.OBFireworksOnJoin"
}